config/routes.rb
Mockingbird::Application.routes.draw do
  get "portfolio/index"

  get "about/index"
  get "services/index"

  get "assets/images"

  get "home/index"

  match 'contact' => 'contact#index', :as => 'contact'
  match 'dispatch_email' => 'contact#dispatch_email', :as => 'dispatch_email', :method => :post

  root :to => 'home#index'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def dispatch_email
    user_info = params(:user_info)
    if ContactMailer.send_email(user_info).deliver
      flash[:notice] = "Mensaje enviado, responderemos a la brevedad."
    else
      flash[:notice] = "): Se genero un problema al procesar tu mensaje, intentalo nuevamente."
    end
    redirect_to index_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/about/index.html.haml
= render "/layouts/header"
.content
  .container-fluid
    .page-header
      %h1 
        ¡Estos somos nosotros!
        %small Nuestro equipo esta formado por jóvenes desarrolladores que aman lo que hacen.
    .row-fluid
      .span8.hero-unit
        %h1 Felipe Cabargas
        %hr
        %p Estudiante de Bachillerato en Ciencias Naturales y Exactas de la Universidad de Chile
        %p UI/UX Designer | Developer en Rails, Python y HTML5
        %h5 
          Twitter: 
          = link_to("@juanpintoduran", "https://www.twitter.com/juanpintoduran")
          | Web: 
          = link_to("http://www.cabargas.com", "http://www.cabargas.com")
        .team
          / = image_tag("felipe.png")
      .span4
    .row-fluid
      .span4
      .span8.hero-unit
        %h1 Nélson Jimenez
        %hr
        %p Estudiante de Ingeniería Civil en Computación de la Universidad Tecnológica de Chile
        %p  Backend ninja | Developer en Rails, PHP, C#
        %h5 
          Twitter: 
          = link_to("@_patojimenez", "https://www.twitter.com/_patojimenez")
          | Web: 
          = link_to("http://www.monoentrenado.com", "http://www.monoentrenado.com")
        .team
          / = image_tag("nelson.png")
    .row-fluid
      .span8.hero-unit
        %h1 Henry López
        %hr
        %p Estudiante de Enseñanza Media en el Instituto Nacional General José Miguel Carrera
        %p Developer en C, PHP+MySQL
        %h5 
          Twitter: 
          = link_to("@Marcianisto", "https://www.twitter.com/Marcianisto")
          | Web: 
          = link_to("http://www.notengopagina.com", :url => "#")
        .team
          / = image_tag("henry.png")
      .span4
= render "/layouts/footer"

app/views/contact/index.html.erb
<%= render "/layouts/header" %>

<%= form_tag dispatch_email_path, method: :post do %>
  <%= label_tag "user_info[name]", "Nombre" %>
  <%= text_field_tag "user_info[name]" %>
  <%= label_tag "user_info[email]", "Email" %>
  <%= text_field_tag "user_info[email]" %>
  <%= label_tag "user_info[message]", "Message" %>
  <%= text_area_tag "user_info[message]", "" %>
  <%= submit_tag "Enviar", :class => "{btn btn-primary btn-large}" %>
<% end %>

<%= render "/layouts/footer" %>

app/views/home/index.html.haml
= render "/layouts/header"
.content
  .container-fluid#clientes
    .page-header
      %h1 
        cada día más clientes felices
      %h1
        %small ellos ya trabajan con nosotros! que esperas tú?
    .row-fluid
      .span3.brand
        %h5
          = image_tag("colapso.png")
        %hr
        %h6 
          = link_to("radiocolapso.com", "http://www.radiocolapso.com")
      .span3.brand
        %h5
          = image_tag("squape.png")
        %hr
        %h6 
          = link_to("squape.com", "http://www.squape.com")
      .span3.brand
        %h5
          = image_tag("menare.png")
        %hr
        %h6 
          = link_to("menare.cl", "http://www.menare.cl")
      .span3.brand
        %h5
          = image_tag("cabargas.png")
        %hr
        %h6 
          = link_to("cabargas.com", "http://www.cabargas.com")
    .page-header
      %h1 
        vamos al grano
      %h1
        %small 'agile development' & responsive design are our commandments
    .row-fluid
      .span4
        %h1.info
          =image_tag("technologies.png")
        %hr
        %p.info Modernización y mantenimiento de webs, implementación de SAaS en Ruby on Rails y PHP en Symfony.
      .span4
        %h1.info
          =image_tag("platforms.png")
        %hr
        %p.info Desarrollo y publicación de aplicaciones nativas y adaptación de webs para iOS, Android y Windows Phone.
      .span4
        %h1.info
          =image_tag("snetworks.png")
        %hr
        %p.info Porque hoy no sólo basta con una web. Diseño, asesorías y planificación de campañas en redes sociales.
    .page-header
      %h1 
        esta es nuestra 'liga de la justicia'
      %h1
        %small nuestro equipo esta formado por jóvenes desarrolladores que aman lo que hacen
    .row-fluid
      .span4.info
        %h1 Felipe Cabargas
        %h4 
          = link_to("felipe@mockingbirdev.com", "mailto:felipe@mockingbirdev.com")
        %hr
        %p Lo que verás, lo hace él... Diseño y programación de interfaces es su campo.
        %p UI/UX Designer | Developer en Rails, Python y HTML5
        %h5 
          Twitter: 
          = link_to("@juanpintoduran", "https://www.twitter.com/juanpintoduran")
          | Web: 
          = link_to("http://www.cabargas.com", "http://www.cabargas.com")
        .team
          / = image_tag("felipe.png")
      .span4.info
        %h1 Nelson Jiménez
        %h4 
          = link_to("nelson@mockingbirdev.com", "mailto:nelson@mockingbirdev.com")
        %hr
        %p Nuestro especialista en Bases de Datos, jerk of all trades.
        %p  Backend ninja | Developer en Rails, PHP, C#
        %h5 
          Twitter: 
          = link_to("@_patojimenez", "https://www.twitter.com/_patojimenez")
          | Web: 
          = link_to("http://www.monoentrenado.com", "http://www.monoentrenado.com")
        .team
          / = image_tag("nelson.png")
      .span4.info
        %h1 Henry López
        %h4 
          = link_to("henry@mockingbirdev.com", "mailto:henry@mockingbirdev.com")
        %hr
        %p Geek 24x7, Henry es el SSH-master de MD, el se encarga del monitoreo y configuración de servers.
        %p Developer en C, PHP+MySQL
        %h5 
          Twitter: 
          = link_to("@Marcianisto", "https://www.twitter.com/Marcianisto")
          | Web: 
          = link_to("http://www.notengopagina.com", :url => "http://marcianisto.mockingbirdev.com")
        .team
          / = image_tag("henry.png")
= render "/layouts/footer"

app/views/home/old_index.html.haml
= render "/layouts/header"
.content
  .big_image
    =image_tag("welove.png")
    =image_tag("resources-big.png")
= render "/layouts/footer"

app/views/layouts/_footer.html.haml
.push
.footer
  .data
    2012 &copy; @MockingbirdDev | mail: contacto@mockingbirdev.com | fono: +56978428435
  %a	
    =image_tag("md-logo.png")
  %a{href: "https://github.com/felipecabargas/mockingbirddev-web"}
    =image_tag("github-logo.png")

app/views/layouts/_header.html.haml
.header
  .banner
    %a{ :href => "#clientes"}
      .title
        =image_tag("title.png")
      .bird
        business meet people
  .navbar
    .navbar-inner
      .container-fluid
        %ul.nav
          %li
            =link_to(('INICIO'), root_path)
          %li
            =link_to(('EQUIPO'), about_index_path)
          %li
            =link_to(('SERVICIOS'), services_index_path)
          %li
            =link_to(('CLIENTES'), portfolio_index_path)
          / %li
          /   =link_to(('Contacto'), contact_path)
    / .division

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mockingbird</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="apple-touch-icon" href="/assets/icon.png"/>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/portfolio/index.html.haml
= render "/layouts/header"
.content
  .container-fluid
    .page-header
      %h1 
        ¡Ellos ya trabajan con nosotros!
        %small Que esperas?
    .row-fluid
      .span4.hero-unit.brand
        %h5
          = image_tag("squape.png")
        %hr
        %h5 Una nueva forma de entender el arriendo de temporada.
        %hr
        %h6 
          Ver proyecto: 
          = link_to("squape.com", "https://www.squape.com")
      .span4.hero-unit.brand
        %h5
          = image_tag("menare.png")
        %hr
        %h5 Sitio Web de campaña de Nicolás Menare para las Elecciones Municipales 2012 de Chile
        %hr
        %h6 
          Ver proyecto: 
          = link_to("menare.cl", "http://www.menare.cl")  
      .span4.hero-unit.brand
        %h5
          = image_tag("colapso.png")
        %hr
        %h5 Radio Online para público juvenil a la cual proveemos de Servidores de Radio de Alta Calidad
        %hr
        %h6 
          Ver proyecto: 
          = link_to("radiocolapso.com", "http://www.radiocolapso.com") 
= render "/layouts/footer"

app/views/services/index.html.haml
= render "/layouts/header"
.content
  .container-fluid
    .page-header
      %h1 
        Nuestros servicios
        %small Agile development & responsive design are our commandments.
    .row-fluid
      .thumbnails
        .span4.thumbnail
          .caption
            %h1.info
              =image_tag("technologies.png")
            %hr
            %p Desarrollamos proyectos con las últimas tecnologías en un ambiente comprometido con las necesidades del cliente.
            %p.info 
              =link_to("Pronto más...")
        .span4.thumbnail
          .caption
            %h1.info
              =image_tag("platforms.png")
            %hr
            %p Conocemos las necesidades del mundo de hoy y sabemos que la web móvil es importante.
            %p.info
              ¿Tu web en dispositivos móviles? Don't Worry! We can make it.
        .span4.thumbnail
          .caption
            %h1.info
              / =image_tag("snetworks.png")
              %a{href: "https://www.facebook.com/pages/Mockingbird-Dev/398379150199100"}
                =image_tag("facebook-but.png")
              %a{href: "https://www.twitter.com/MockingbirdDev"}
                =image_tag("twitter-but.png")
              %a{href: "https://plus.google.com/b/116381271887702655354/116381271887702655354/posts"}
                =image_tag("gplus-but.png")
            %hr
            %p No eres un gran fan de las redes sociales?... Utiliza a nuestro formulario de contacto (arriba) o envía un mail a:
            %p.info
              =link_to("contacto@mockingbirdev.com", "mailto:contacto@mockingbirdev.com")
= render "/layouts/footer"